on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          repository: hk-modding/modlinks
      - name: execute python updates
        run: |
          curl "https://gist.githubusercontent.com/Bentechy66/c1add43ce3e045a95d4d868fc8c2cb02/raw/676278218a67c9c479055e9c49f77e68baf546e7/modlinks_update_script.py" | python
        env:
          ASSETS: ${{ toJSON(github.event.release.assets) }}
          VERSION: ${{ github.event.release.name }}
      - name: commit
        run: git config --global user.name "BenTechy Service Account" && git config --global user.email "ben.griffiths@ada.ac.uk" && git add . && git commit -m "Update BWR Version"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.AccessToken }}
          title: Update Breakable Wall Randomiser
          body: Auto-generated PR on release.
          push-to-fork: bentechy-service-account/modlinks
          branch-suffix: short-commit-hash
